services:
  wp-db:
    image: mariadb
    container_name: wp_db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=[DB_ROOT_PASSWORD]
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=[DB_PASSWORD]
    expose:
      - 3306
      - 33060
  wp-app:
    image: wordpress
    container_name: wp_app
    volumes:
      - app_data:/var/www/html
      # - ~/dev/docker/.out:/out
    ports:
      - 8001:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=[DB_PASSWORD]
      - WORDPRESS_DB_NAME=wordpress
  wp-cli:
    image: wordpress:cli
    container_name: wp_cli
    user: '33:33'
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=[DB_PASSWORD]
      - WORDPRESS_DB_NAME=wordpress
    volumes_from:
      - wp-app
volumes:
  db_data:
  app_data:
